export const LIST_ALL_PROFILE_NOTES = 'LIST_ALL_PROFILE_NOTES';
export const ADD_NEW_PROFILE_NOTE = 'ADD_NEW_PROFILE_NOTE';
export const REMOVE_EXISTING_PROFILE_NOTE = 'REMOVE_EXISTING_PROFILE_NOTE';

// PROFILE EDIT INPUT_FIELDS
export const LIST_ALL_INPUT_FIELDS = 'LIST_ALL_INPUT_FIELDS';
export const ADD_NEW_INPUT_FIELD = 'ADD_NEW_INPUT_FIELD';
export const REMOVE_EXISTING_INPUT_FIELD = 'REMOVE_EXISTING_INPUT_FIELD';

// PROFILE EDIT
export const UPDATE_PROFILE_EDIT = 'UPDATE_PROFILE_EDIT';
export const LIST_ALL_GENRES = 'LIST_ALL_GENRES';
export const ADD_NEW_GENRE = 'ADD_NEW_GENRE';
export const REMOVE_EXISTING_GENRE = 'REMOVE_EXISTING_GENRE;'

// WORDS
export const LIST_ALL_WORDS = 'LIST_ALL_WORDS';
export const ADD_NEW_WORD = 'ADD_NEW_WORD';
export const REMOVE_EXISTING_WORD = 'REMOVE_EXISTING_WORD';

// FRONT_PAGE
export const LIST_ALL_FRONT_PAGE_DEMO_BOOKS = 'LIST_ALL_FRONT_PAGE_DEMO_BOOKS';

// DASHBOARD
export const LIST_ALL_DASHBOARD_BOOK = 'LIST_ALL_DASHBOARD_BOOK';
export const ADD_NEW_DASHBOARD_BOOK = 'ADD_NEW_DASHBOARD_BOOK';
export const REMOVE_NEW_DASHBOARD_BOOK = 'REMOVE_NEW_DASHBOARD_BOOK';
export const SELECTED_BOOK = 'SELECTED_BOOK';

// SEARCH
export const LIST_ALL_SEARCH_MATERIALS = 'LIST_ALL_SEARCH_MATERIALS';

// OTHER_FEATURES
export const LIST_ALL_OTHER_FEATURES = 'LIST_ALL_OTHER_FEATURES';

// FORUM
export const LIST_ALL_FORUM_TIPS = 'LIST_ALL_FORUM_TIPS';
export const ADD_NEW_FORUM_TIP = 'ADD_NEW_FORUM_TIP';

// USER_STORIES
export const ADD_NEW_USER_STORIE = 'ADD_NEW_USER_STORIE';
export const ADD_NEW_USER = 'ADD_NEW_USER';